// Auto-generated by scripts/sync-content-types.mjs. DO NOT EDIT BY HAND.
// Sources: e-commerce-backend/src/content/content-defaults.service.ts, e-commerce-backend/src/content/legacy-content.service.ts, e-commerce-backend/src/content/content-migrations.service.ts, e-commerce-backend/src/modules/hero/hero.service.ts
// Mirrors ContentRegistryService.register() calls in NestJS modules.
// Run `npm run sync:content-types` to regenerate after adding keys.
export interface ContentKeys {
  // about
  'about.foundation.image': { type: 'image' };
  'about.foundation.label': { type: 'text'; locales: ['en', 'ar'] };
  'about.foundation.text1': { type: 'text'; locales: ['en', 'ar'] };
  'about.foundation.text2': { type: 'text'; locales: ['en', 'ar'] };
  'about.foundation.title': { type: 'text'; locales: ['en', 'ar'] };
  'about.founder.letter': { type: 'text'; locales: ['en', 'ar'] };
  'about.founder.note.heading': { type: 'text'; locales: ['en', 'ar'] };
  'about.founder.signature.image': { type: 'image' };
  'about.hero.cta': { type: 'text'; locales: ['en', 'ar'] };
  'about.hero.headline': { type: 'text'; locales: ['en', 'ar'] };
  'about.hero.image': { type: 'image' };
  'about.intentional.image': { type: 'image' };
  'about.intentional.text': { type: 'text'; locales: ['en', 'ar'] };
  'about.intentional.title': { type: 'text'; locales: ['en', 'ar'] };
  'about.team.description': { type: 'text'; locales: ['en', 'ar'] };
  'about.team.label': { type: 'text'; locales: ['en', 'ar'] };
  'about.team.member1.image': { type: 'image' };
  'about.team.member1.name': { type: 'text'; locales: ['en', 'ar'] };
  'about.team.member1.title': { type: 'text'; locales: ['en', 'ar'] };
  'about.team.member2.image': { type: 'image' };
  'about.team.member2.name': { type: 'text'; locales: ['en', 'ar'] };
  'about.team.member2.title': { type: 'text'; locales: ['en', 'ar'] };
  'about.team.member3.image': { type: 'image' };
  'about.team.member3.name': { type: 'text'; locales: ['en', 'ar'] };
  'about.team.member3.title': { type: 'text'; locales: ['en', 'ar'] };
  'about.team.title': { type: 'text'; locales: ['en', 'ar'] };
  'about.values.image': { type: 'image' };

  // auth
  'auth.heading.account': { type: 'text'; locales: ['en', 'ar'] };
  'auth.heading.login': { type: 'text'; locales: ['en', 'ar'] };
  'auth.heading.signup': { type: 'text'; locales: ['en', 'ar'] };
  'auth.login.image': { type: 'image' };
  'auth.login.tagline': { type: 'text'; locales: ['en', 'ar'] };
  'auth.placeholder.email': { type: 'text'; locales: ['en', 'ar'] };
  'auth.placeholder.name': { type: 'text'; locales: ['en', 'ar'] };
  'auth.placeholder.password': { type: 'text'; locales: ['en', 'ar'] };
  'auth.placeholder.phone': { type: 'text'; locales: ['en', 'ar'] };
  'auth.sign.out': { type: 'text'; locales: ['en', 'ar'] };
  'auth.signed.in.as': { type: 'text'; locales: ['en', 'ar'] };
  'auth.submit.login': { type: 'text'; locales: ['en', 'ar'] };
  'auth.submit.signup': { type: 'text'; locales: ['en', 'ar'] };
  'auth.toggle.to.login': { type: 'text'; locales: ['en', 'ar'] };
  'auth.toggle.to.register': { type: 'text'; locales: ['en', 'ar'] };

  // cart
  'cart.bag.label': { type: 'text'; locales: ['en', 'ar'] };
  'cart.checkout.label': { type: 'text'; locales: ['en', 'ar'] };
  'cart.continue.shopping': { type: 'text'; locales: ['en', 'ar'] };
  'cart.empty.drawer': { type: 'text'; locales: ['en', 'ar'] };
  'cart.shipping.disclaimer': { type: 'text'; locales: ['en', 'ar'] };
  'cart.shipping.unlocked.text': { type: 'text'; locales: ['en', 'ar'] };

  // checkout
  'checkout.back.to.shop': { type: 'text'; locales: ['en', 'ar'] };
  'checkout.card.label': { type: 'text'; locales: ['en', 'ar'] };
  'checkout.cod.label': { type: 'text'; locales: ['en', 'ar'] };
  'checkout.confirmed.heading': { type: 'text'; locales: ['en', 'ar'] };
  'checkout.confirmed.message': { type: 'text'; locales: ['en', 'ar'] };
  'checkout.heading': { type: 'text'; locales: ['en', 'ar'] };
  'checkout.nav.back': { type: 'text'; locales: ['en', 'ar'] };
  'checkout.nav.continue': { type: 'text'; locales: ['en', 'ar'] };
  'checkout.payment.heading': { type: 'text'; locales: ['en', 'ar'] };
  'checkout.paypal.label': { type: 'text'; locales: ['en', 'ar'] };
  'checkout.place.order': { type: 'text'; locales: ['en', 'ar'] };
  'checkout.review.heading': { type: 'text'; locales: ['en', 'ar'] };
  'checkout.shipping.heading': { type: 'text'; locales: ['en', 'ar'] };
  'checkout.submitting.text': { type: 'text'; locales: ['en', 'ar'] };
  'checkout.terms.text': { type: 'text'; locales: ['en', 'ar'] };

  // contact
  'contact.email': { type: 'text'; locales: ['en', 'ar'] };
  'contact.email.label': { type: 'text'; locales: ['en', 'ar'] };
  'contact.faq.cta': { type: 'text'; locales: ['en', 'ar'] };
  'contact.faq.text': { type: 'text'; locales: ['en', 'ar'] };
  'contact.faq.title': { type: 'text'; locales: ['en', 'ar'] };
  'contact.hero.heading': { type: 'text'; locales: ['en', 'ar'] };
  'contact.hero.image': { type: 'image' };
  'contact.info.title': { type: 'text'; locales: ['en', 'ar'] };
  'contact.support.hours': { type: 'text'; locales: ['en', 'ar'] };
  'contact.support.info': { type: 'text'; locales: ['en', 'ar'] };
  'contact.wholesale.email': { type: 'text'; locales: ['en', 'ar'] };
  'contact.wholesale.label': { type: 'text'; locales: ['en', 'ar'] };

  // faq
  'faq.hero.title': { type: 'text'; locales: ['en', 'ar'] };
  'faq.hero.subtitle': { type: 'text'; locales: ['en', 'ar'] };

  // footer
  'footer.columns.title.navigate': { type: 'text'; locales: ['en', 'ar'] };
  'footer.columns.title.official': { type: 'text'; locales: ['en', 'ar'] };
  'footer.columns.title.social': { type: 'text'; locales: ['en', 'ar'] };
  'footer.columns.title.support': { type: 'text'; locales: ['en', 'ar'] };
  'footer.cookie.link': { type: 'text'; locales: ['en', 'ar'] };
  'footer.copyright': { type: 'text'; locales: ['en', 'ar'] };
  'footer.country.region': { type: 'text'; locales: ['en', 'ar'] };
  'footer.email.placeholder': { type: 'text'; locales: ['en', 'ar'] };
  'footer.link.accessibility': { type: 'text'; locales: ['en', 'ar'] };
  'footer.link.contact': { type: 'text'; locales: ['en', 'ar'] };
  'footer.link.faq': { type: 'text'; locales: ['en', 'ar'] };
  'footer.link.find.us': { type: 'text'; locales: ['en', 'ar'] };
  'footer.link.privacy': { type: 'text'; locales: ['en', 'ar'] };
  'footer.link.shop': { type: 'text'; locales: ['en', 'ar'] };
  'footer.link.story': { type: 'text'; locales: ['en', 'ar'] };
  'footer.link.terms': { type: 'text'; locales: ['en', 'ar'] };
  'footer.link.vlog': { type: 'text'; locales: ['en', 'ar'] };
  'footer.newsletter.subtitle': { type: 'text'; locales: ['en', 'ar'] };
  'footer.newsletter.text': { type: 'text'; locales: ['en', 'ar'] };
  'footer.privacy.notice': { type: 'text'; locales: ['en', 'ar'] };
  'footer.subscribe.btn': { type: 'text'; locales: ['en', 'ar'] };
  'footer.support.hours': { type: 'text'; locales: ['en', 'ar'] };
  'footer.support.subtext': { type: 'text'; locales: ['en', 'ar'] };

  // home
  'home.commitment.cta': { type: 'text'; locales: ['en', 'ar'] };
  'home.commitment.headline': { type: 'text'; locales: ['en', 'ar'] };
  'home.commitment.image': { type: 'image' };
  'home.commitment.mission.cta': { type: 'text'; locales: ['en', 'ar'] };
  'home.commitment.mission.detail': { type: 'text'; locales: ['en', 'ar'] };
  'home.commitment.mission.title': { type: 'text'; locales: ['en', 'ar'] };
  'home.commitment.philanthropy.cta': { type: 'text'; locales: ['en', 'ar'] };
  'home.commitment.philanthropy.detail': { type: 'text'; locales: ['en', 'ar'] };
  'home.commitment.philanthropy.title': { type: 'text'; locales: ['en', 'ar'] };
  'home.commitment.sustainability.cta': { type: 'text'; locales: ['en', 'ar'] };
  'home.commitment.sustainability.detail': { type: 'text'; locales: ['en', 'ar'] };
  'home.commitment.sustainability.title': { type: 'text'; locales: ['en', 'ar'] };
  'home.faq.image': { type: 'image' };
  'home.hero.announcement': { type: 'text'; locales: ['en', 'ar'] };
  'home.hero.cta': { type: 'text'; locales: ['en', 'ar'] };
  'home.hero.headline': { type: 'text'; locales: ['en', 'ar'] };
  'home.hero.image': { type: 'image' };
  'home.hero.image.mobile': { type: 'image' };
  'home.hero.image.tablet': { type: 'image' };
  'home.hero.scroll.hint': { type: 'text'; locales: ['en', 'ar'] };
  'home.hero.subtitle': { type: 'text'; locales: ['en', 'ar'] };
  'home.marquee.text': { type: 'text'; locales: ['en', 'ar'] };
  'home.ourstory.image': { type: 'image' };
  'home.philosophy.cta': { type: 'text'; locales: ['en', 'ar'] };
  'home.philosophy.headline': { type: 'text'; locales: ['en', 'ar'] };
  'home.philosophy.image': { type: 'image' };
  'home.philosophy.text': { type: 'text'; locales: ['en', 'ar'] };
  'home.promo.badge': { type: 'text'; locales: ['en', 'ar'] };
  'home.promo.cta': { type: 'text'; locales: ['en', 'ar'] };
  'home.promo.description': { type: 'text'; locales: ['en', 'ar'] };
  'home.promo.headline': { type: 'text'; locales: ['en', 'ar'] };
  'home.promo.image': { type: 'image' };
  'home.shop.image': { type: 'image' };
  'home.showcase.empty': { type: 'text'; locales: ['en', 'ar'] };
  'home.social.cta': { type: 'text'; locales: ['en', 'ar'] };
  'home.social.heading': { type: 'text'; locales: ['en', 'ar'] };
  'home.social.image1': { type: 'image' };
  'home.social.image2': { type: 'image' };
  'home.social.image3': { type: 'image' };
  'home.social.image4': { type: 'image' };
  'home.story.image': { type: 'image' };
  'home.trending.title': { type: 'text'; locales: ['en', 'ar'] };

  // marketing
  'marketing.announcement.text': { type: 'text'; locales: ['en', 'ar'] };
  'marketing.site.logo.image': { type: 'image' };
  'marketing.site.name': { type: 'text'; locales: ['en', 'ar'] };
  'marketing.store.locator.no.results': { type: 'text'; locales: ['en', 'ar'] };
  'marketing.store.locator.tagline': { type: 'text'; locales: ['en', 'ar'] };

  // product
  'product.add.to.bag': { type: 'text'; locales: ['en', 'ar'] };
  'product.afterpay.text': { type: 'text'; locales: ['en', 'ar'] };
  'product.buy.now': { type: 'text'; locales: ['en', 'ar'] };
  'product.details.fallback': { type: 'text'; locales: ['en', 'ar'] };
  'product.no.reviews': { type: 'text'; locales: ['en', 'ar'] };
  'product.rating.label': { type: 'text'; locales: ['en', 'ar'] };
  'product.select.option': { type: 'text'; locales: ['en', 'ar'] };
  'product.sold.out': { type: 'text'; locales: ['en', 'ar'] };
  'product.unavailable.cta': { type: 'text'; locales: ['en', 'ar'] };
  'product.unavailable.desc': { type: 'text'; locales: ['en', 'ar'] };
  'product.unavailable.headline': { type: 'text'; locales: ['en', 'ar'] };

  // review
  'review.filter.button': { type: 'text'; locales: ['en', 'ar'] };
  'review.filter.stars': { type: 'text'; locales: ['en', 'ar'] };
  'review.helpful.question': { type: 'text'; locales: ['en', 'ar'] };
  'review.hydration.question': { type: 'text'; locales: ['en', 'ar'] };
  'review.load.more': { type: 'text'; locales: ['en', 'ar'] };
  'review.show.less': { type: 'text'; locales: ['en', 'ar'] };
  'review.show.more': { type: 'text'; locales: ['en', 'ar'] };
  'review.sort.helpful': { type: 'text'; locales: ['en', 'ar'] };
  'review.sort.highest': { type: 'text'; locales: ['en', 'ar'] };
  'review.sort.lowest': { type: 'text'; locales: ['en', 'ar'] };
  'review.sort.recent': { type: 'text'; locales: ['en', 'ar'] };
  'review.verified.label': { type: 'text'; locales: ['en', 'ar'] };
  'review.write.button': { type: 'text'; locales: ['en', 'ar'] };

  // search
  'search.brands.heading': { type: 'text'; locales: ['en', 'ar'] };
  'search.collections.heading': { type: 'text'; locales: ['en', 'ar'] };
  'search.collections.unavailable': { type: 'text'; locales: ['en', 'ar'] };
  'search.drawer.title': { type: 'text'; locales: ['en', 'ar'] };
  'search.no.results': { type: 'text'; locales: ['en', 'ar'] };
  'search.placeholder': { type: 'text'; locales: ['en', 'ar'] };
  'search.products.heading': { type: 'text'; locales: ['en', 'ar'] };

  // shop
  'shop.active.filters': { type: 'text'; locales: ['en', 'ar'] };
  'shop.back.to.all': { type: 'text'; locales: ['en', 'ar'] };
  'shop.clear.all': { type: 'text'; locales: ['en', 'ar'] };
  'shop.empty.all': { type: 'text'; locales: ['en', 'ar'] };
  'shop.empty.filtered': { type: 'text'; locales: ['en', 'ar'] };
  'shop.show.more': { type: 'text'; locales: ['en', 'ar'] };
  'shop.sort.label': { type: 'text'; locales: ['en', 'ar'] };

  // vlog
  'vlog.hero.image': { type: 'image' };
  'vlog.hero.title': { type: 'text'; locales: ['en', 'ar'] };

  // wishlist
  'wishlist.empty': { type: 'text'; locales: ['en', 'ar'] };
  'wishlist.empty.subtext': { type: 'text'; locales: ['en', 'ar'] };
  'wishlist.recommendations.title': { type: 'text'; locales: ['en', 'ar'] };
}
