/**
 * NOT_MIGRATED — spec 005 (C-10 / FR-017) generated ledger.
 *
 * Each entry is a component → fields[] that still imports useSiteContent.
 * CI fails the build when this list contains non-acknowledged entries.
 *
 * Generated by: scripts/audit-use-site-content.mjs
 * Regenerate:  npm run audit:use-site-content
 */
export const NOT_MIGRATED = {
} as const;

/** Components whose remaining useSiteContent fields are all in the acknowledged list. */
export const MIGRATED = ["AboutPage","AccountPage","Cart","CartDrawer","ContactPage","Footer","Hero","IcareProductRoutePage","PhilosophySection","ProductPage","ProductShowcase","PromoSection","SearchDrawer","ShopPage","SocialGrid","StoreLocator","VlogPage","WishlistPage","WriteReviewDialog"] as const;
